---
- name: Clean the environment
  hosts: localhost
  vars_files:
    - ../keycred
  environment:
    AWS_ACCESS_KEY_ID: "{{ USER }}"
    AWS_SECRET_ACCESS_KEY: "{{ PASSWORD }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Terminate every 'running' instance
    ec2_instance:
      state: absent
      filters:
        instance-state-name: running
      region: us-east-2

  - name: Gather info about the volumes
    ec2_vol_info:
      filters:
        status: available
      region: us-east-2
    register: output

  - name: Delete extra volumes
    ec2_vol:
      id: "{{ item }}"
      instance: None
      state: absent
      region: us-east-2
    loop:
      - "{{ output.volumes[0].id }}"
      - "{{ output.volumes[1].id }}"
    when: output is failed