---
- name: Clean the environment
  hosts: localhost
  vars_files:
    - ../keycred
  environment:
    AWS_ACCESS_KEY_ID: "{{ USER }}"
    AWS_SECRET_ACCESS_KEY: "{{ PASSWORD }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Terminate instances
      ec2_instance:
        state: absent
        filters:
          instance-state-name: running
        region: us-east-2        