---
- name: F2
  hosts: localhost
  vars_files:
    - ../keycred
  environment:
    AWS_ACCESS_KEY_ID: "{{ USER }}"
    AWS_SECRET_ACCESS_KEY: "{{ PASSWORD }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instances_ids: "{{ INSTANCE_IDS }}"
    instance_type: "{{ INSTANCE_TYPE | default( INSTANCE_TYPE_DEFAULT , true) }}"
    instance_image: "{{ INSTANCE_IMAGE | default( INSTANCE_IMAGE_DEFAULT , true) }}"
  tasks:
    #    - name: create instance
    #      ec2:
    #        instance_type: "{{ instance_type }}"
    #        image: "{{ instance_image }}"
    #        region: yourregion

    #    - name: create keypair
    #      ec2_key:
    #        name: kkey
    #        key_material: 'yourpublicid'
    #        region: yourregion

    #    - name: terminate instance
    #      ec2:
    #        state: 'absent'
    #        instance_ids: "{{ instances_ids }}"
    #        region: yourregion
