---
- name: F2
  hosts: localhost
  vars_files:
    - ../keycred
  environment:
    AWS_ACCESS_KEY_ID: "{{ USER }}"
    AWS_SECRET_ACCESS_KEY: "{{ PASSWORD }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instance_type: "{{ INSTANCE_TYPE | default( 't2.micro' ) }}"
    instance_image: "{{ INSTANCE_IMAGE | default( 'ami-0f5457ab1b6214674' ) }}"
  tasks:
    - name: Terminate all instances
      ec2_instance:
        state: absent
        filters:
          instance-state-name: running
        region: yourregion
      register: output

    - debug:
        msg: '{{ output }}'

        #    - name: create instance
        #      ec2:
        #        instance_type: "{{ instance_type }}"
        #        image: "{{ instance_image }}"
        #        region: yourregion
        #        count: 3
        #      register: output

    #    - name: create keypair
    #      ec2_key:
    #        name: kkey
    #        key_material: 'yourpublicid'
    #        region: yourregion

        #    - name: wait 1 min
        #      command: >
        #        sleep 60
        
        #    - name: terminate instance
        #      ec2:
        #        state: 'absent'
        #        instance_ids: "{{ output.instances[0].id }}"
        #        region: yourregion

